### PR TITLE
fixed get_columns to support views, not just tables

### PR DESCRIPTION
**Pull request by dennisobrien**
The function `get_columns` previously only supported tables, not views.  The underlying table `v_catalog.columns` only has information for columns belonging to tables.  The table `v_catalog.view_columns` is the analog for columns belonging to views.

This change queries both of these tables for column information.

I made my best guess at what the values for `column_default` and `is_nullable` should be.  If you have suggestions for changes, I am open.

Since views cannot have primary keys I didn't change the logic behind that query.

Here's the test I ran.

```
import os
from sqlalchemy import create_engine, Table, MetaData


def get_sqla_engine():
    # replace your vertica credentials here
    url = 'vertica+vertica_python://VERTICA_USERNAME:VERTICA_PASSWORD@VERTICA_HOST:5433/db'
    return create_engine(url)


def test_get_table():
    # replace with the view name and schema
    schema = 'MY_SCHEMA'
    table_name = 'MY_VIEW_NAME'
    meta = MetaData()
    table = Table(table_name, meta, schema=schema or None, autoload=True, autoload_with=get_sqla_engine())
    print(table)

test_get_table()
```

Let me know if I can help to answer any questions.

### CODE REVIEW

**Comment by dennisobrien** [comment]
Is this project still being maintained?  I would be great to merge the PRs that are in the queue.  I'd be happy to help.

**Comment by lemeryfertitta** [comment]
@dennisobrien sorry for the lack of response, I wasn't getting notifications from this for a while.

We're happy to continue maintaining the project. I'll check out the PRs in the repo in the next few days.

**Comment by dennisobrien** [comment]
@lemeryfertitta No problem, I completely understand.  I know there are a lot of other folks in the world like myself who have benefited from your work here, so don't hesitate to draft us into helping with testing, documentation, whatever.

**Comment by lemeryfertitta** [comment]
@dennisobrien thanks! I took the opportunity to clean up the code in this method and merged it. I'll package up a new pypi release after the remaining PRs and issues are sorted out.

**Pull request merged**
